### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by souris-dev** [soumya17052002/Chat-App#1]
The README could be fixed to include a proper description of the app.

**Comment by nexus-hash** [comment]
@souris-dev  If you can, A Pull Request is most welcomed.

**Comment by souris-dev** [comment]
@soumya17052002 Sure, I'll open one when fixed.

**Comment by nexus-hash** [comment]
Hey, @souris-dev I am Closing this issue since README is fixed and app documentation will be added soon.
You can find it [here](https://github.com/soumya17052002/Chat-App/commit/98ef1b36d394cffe060c488081a4ed9ad4bd8b1c).
